name: "LibertAI Agent Deployment"
description: "Deploy an agent using libertAI"
author: "LibertAI"
branding:
  icon: upload-cloud
  color: blue

inputs:
  agent-id:
    required: true
    default: ""
    description: "ID that will be used to deploy the agent"
  agent-secret:
    required: true
    default: ""
    description: "Secret that will be used to deploy the agent"
  dependency-management-tool:
    required: false
    default: "poetry"
    description: "Package manager used to handle dependencies"
  python-version:
    required: false
    default: "3.13.3"
    description: "Version to deploy with"
  usage-type:
    required: false
    default: "fastapi"
    description: "How the agent is called"
  agent-environment:
    required: false
    default: ""
    description: "If provided, your agent will have access to this environment"

outputs:
  agent-deployment-success:
    description: "Agent sucess status when deployed"
    value: ${{ steps.agent-deployment.outputs.agent-deployment-success }}
  agent-message:
    description: "Message got when trying to deploy your agent using the libertAI's CLI"
    value: ${{ steps.agent-deployment.outputs.agent-deployment-message }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install libertAI CLI
      run: pip install libertai-client==0.1.3
      shell: bash

    - name: Initialize and Deploy Agent
      id: agent-deployment
      run: |
        echo "LIBERTAI_AGENT_ID=${{ inputs.agent-id }}" > .env.libertai
        echo "LIBERTAI_AGENT_SECRET=${{ inputs.agent-secret }}" >> .env.libertai
        if [ -n "${{ inputs.agent-environment }}" ]; then
          echo "${{ inputs.agent-environment }}" > .env
        fi
        result=$(libertai agent deploy \
          --dependencies-management="${{ inputs.dependency-management-tool }}" \
          --python-version="${{ inputs.python-version }}" \
          --usage-type="${{ inputs.usage-type }}" \
          .
        )
        success=$(echo $result | jq .success)
        message=$(echo $result | jq .message)
        url=$(echo $result | jq .url)
        error_log=$(echo $result | jq .error_log)

        echo "agent-deployment-success=$success" >> "$GITHUB_OUTPUT"
        echo "agent-deployment-message=${$message} ${error_log}" >> "$GITHUB_OUTPUT"

        if [ $success == "false" ]
        then
          echo ::error $message $error_log
        fi 
      shell: bash
