name: "LibertAI Agent Deployment"
description: "Deploy an agent using libertAI"
author: "LibertAI"
branding:
  icon: upload-cloud
  color: blue

inputs:
  agent-id:
    required: true
    default: ""
    description: "ID that will be used to deploy the agent"
  agent-secret:
    required: true
    default: ""
    description: "Secret that will be used to deploy the agent"
  dependency-management-tool:
    required: false
    default: "poetry"
    description: "Package manager used to handle dependencies"
  python-version:
    required: false
    default: "3.13.3"
    description: "Version to deploy with"
  usage-type:
    required: false
    default: "fastapi"
    description: "How the agent is called"
  agent-environment:
    required: false
    default: ""
    description: "If provided, your agent will have access to this environment"

#outputs:
#  agent-instance:
  #    description: "Agent instance url using ipv6 where you'll be able to communicate with"
  #    value: ${{ steps.agent-deployment.outputs.agent-deployment-url }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install libertAI CLI
      run: pip install libertai-client==0.1.3
      shell: bash

    - name: Initialize and Deploy Agent
      id: agent-deployment
      run: |
        echo "LIBERTAI_AGENT_ID=${{ inputs.agent-id }}" > .env.libertai
        echo "LIBERTAI_AGENT_SECRET=${{ inputs.agent-secret }}" >> .env.libertai
        if [ -n "${{ inputs.agent-environment }}" ]; then
          echo "${{ inputs.agent-environment }}" > .env
        fi
        libertai agent deploy \
        --dependencies-management="${{ inputs.dependency-management-tool }}" \
        --python-version="${{ inputs.python-version }}" \
        --usage-type="${{ inputs.usage-type }}" \
      shell: bash
