name: "Agent deployment"
description: "Deploy an agent on Aleph"

on:
  workflow_call:
    inputs:
      redeploy-if-alive:
        required: true
        type: boolean
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Agent deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout into the respository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.3
      - name: Install libertAI CLI
        run: pip install libertai-client